version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies using node 18"
      - npm install --legacy-peer-deps
      - echo "Done installing dependencies ====>"
  build:
    commands:
      - echo "Building the React project"
      - node --max-old-space-size=4096 node_modules/vite/bin/vite.js build
      - echo "Done building the project ==> Exporting artifacts"

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: dist
