version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing source NPM dependencies...
      - npm install --legacy-peer-deps
  build:
    commands:
      - echo Build started on `date`
      - node --max-old-space-size=4096 node_modules/vite/bin/vite.js build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Checking if build directory exists...
      - if [ -d "dist" ]; then echo "Build directory exists"; else echo "Build directory does not exist"; exit 1; fi
      - echo Archiving artifacts...
      - zip -r dist.zip dist/
artifacts:
  files:
    - '**/*'
  base-directory: dist
 
